logging:
  level:
    org:
      springframework: debug
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  security:
    user:
      name: username
      password: password
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
