logging:
  level:
    org:
      springframework: debug
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: 'false'
management:
  endpoints:
    web:
      exposure:
        include: '*'